# Generated by Django 2.2.10 on 2020-03-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_counter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket_counter_date', models.DateTimeField(blank=True, null=True, verbose_name='Counter datetime for ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
