# Generated by Django 2.2 on 2020-02-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='Published date')),
                ('title', models.CharField(max_length=255, verbose_name='News title')),
                ('text', models.TextField(verbose_name='Content')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
