# Generated by Django 2.2 on 2020-03-01 22:41

import adler.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=adler.news.models.upload_handler),
        ),
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published date'),
        ),
        migrations.AlterModelTable(
            name='news',
            table='all_news',
        ),
    ]
