# Generated by Django 2.2.10 on 2020-09-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200302_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'All news'},
        ),
    ]
