# Generated by Django 2.2.10 on 2020-10-07 19:47

import adler.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200921_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=adler.news.models.upload_handler)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
    ]
