# Generated by Django 2.2.10 on 2020-10-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201007_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
