# Generated by Django 2.2.10 on 2020-10-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_images_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
